name: Publish current PDF
permissions:
  contents: write
on:
  push:
#    branches:
#    - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Get current time
      run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
    - name: Set up Git repository
      uses: actions/checkout@v6
    - name: Compile source
      uses: xu-cheng/latex-action@v4
      with:
        root_file: main.tex
        extra_system_packages: texmf-dist-latexextra
    - name: Upload PDF file
      uses: actions/upload-artifact@v6
      with:
        name: PDF
        path: main.pdf
    - name: Bump version and push tag
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ github.token }}
        custom_tag: ${{ env.NOW }}
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: main.pdf
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
        draft: false
        prerelease: false
